### ISSUE TITLE
The scores are presented in the form of a ‘score board’ where the top guesser is on position 1. etc.

### ISSUE THREAD

**Issue by radubauzh** [sopra-fs22-group-27/Pictionary-Client#12]

**Comment by sumsumcity** [comment]
This means during the game right? @radubauzh

**Comment by sumsumcity** [comment]
@radubauzh I created the scoreboard during game but it is still not sorted...

**Comment by radubauzh** [comment]
@sumsumcity I'll look at it this saturday

**Comment by radubauzh** [comment]
@sumsumcity as discussed, the scoreboard is already sorted.
