### ISSUE TITLE
Sometimes a email is valid in the frontend but invalid in the backend

### ISSUE THREAD

**Issue by sumsumcity** [sopra-fs22-group-27/Pictionary-Client#125]

**Comment by radubauzh** [comment]
Should this task be in backend? 
Can you give some context what kind of emails are not valid in the backend? We could just use the same regex checker in the backend as we use in our frontend
@sumsumcity

**Comment by sumsumcity** [comment]
Jap the problem is that some emails are valid in the frontent but invalid in the backend. But yeah it a small bug and easy to fix
