### ISSUE TITLE
Improve UpdateUserStatus (Logout)

### ISSUE THREAD

**Issue by sumsumcity** [sopra-fs22-group-27/Pictionary-Client#28]
Frontend:
There is a status in the requestBody which doesnt exist in the Backend. Until now after the putRequest the status is automatically to OFFLINE even without the status in the requestBody. 

Perhaps it is solved if we add the status in UserPostDTO and operate with that in the Backend. 

Backend:
Change /status/{token} request. No need for Body and no content status. Also create errors because now it gets a 500 error. Also adjust return value.

**Comment by radubauzh** [comment]
Will you take care of this? @sumsumcity

**Comment by sumsumcity** [comment]
> Will you take care of this? @sumsumcity

yep i can do it @radubauzh
