### ISSUE TITLE
Navigation Issues [HomePage, UserList etc.]

### ISSUE THREAD

**Issue by radubauzh** [sopra-fs22-group-27/Pictionary-Client#55]
- [x] Fix Navigation issues and redirect users to the right pages
- [ ] Delete State from localhost after logout

**Comment by radubauzh** [comment]
@SyLi9527 We leave it in there for Sprint 1 right?

**Comment by SyLi9527** [comment]
@radubauzh Let me try to fix it on another machine tonight

**Comment by SyLi9527** [comment]
@radubauzh fixed. The reason why localstorage remains before is that Nav.Link won't execute onClick function and turn to herf link directly. Now it's changed to as={Link} and works. You can have a test on heroku.
